import { MOCK_REPORTS } from "@/app/lib/mock-data";
import { BookOpen, Users, TrendingUp, ArrowRight, Pencil } from "lucide-react";

export default async function PrintPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const report = MOCK_REPORTS.find((r) => r.id === id);
  if (!report) return <p>Report not found.</p>;

  const d = report.draft_content;

  return (
    <>
      <style>{`
        @media print {
          body { background: white !important; }
          .no-print { display: none !important; }
        }
      `}</style>

      <div className="max-w-[680px] mx-auto p-8 bg-white min-h-screen print:p-0 font-[Inter,system-ui,sans-serif]">
        {/* Header */}
        <div className="flex items-start justify-between mb-8 pb-6 border-b border-gray-200">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <span className="w-6 h-6 rounded-full bg-[#FF6B1F] flex items-center justify-center text-white font-bold text-[10px]">S</span>
              <span className="text-[10px] font-semibold text-gray-400 uppercase tracking-widest">Sheldon Labs · Super Sheldon</span>
            </div>
            <h1 className="text-2xl font-bold text-gray-900" style={{ fontFamily: "'Plus Jakarta Sans', Inter, system-ui" }}>
              {d.header.student_name}
            </h1>
            <p className="text-sm text-gray-500 mt-0.5">
              {d.header.subject} · {d.header.teacher_name}
            </p>
          </div>
          <div className="text-right">
            <p className="text-[10px] text-gray-400 uppercase tracking-widest">Reporting Period</p>
            <p className="font-semibold text-gray-700">{d.header.reporting_month}</p>
          </div>
        </div>

        {/* Sessions & Attendance */}
        <PrintSection icon={<Users size={14} />} title="Sessions & Attendance">
          <div className="grid grid-cols-3 gap-3">
            <PrintStat label="Classes conducted" value={d.sessions_attendance.total_classes} />
            <PrintStat label="Attendance" value={`${d.sessions_attendance.attendance_pct}%`} />
            <PrintStat label="No-shows" value={d.sessions_attendance.no_shows} />
          </div>
        </PrintSection>

        {/* Learning Coverage */}
        <PrintSection icon={<BookOpen size={14} />} title="Learning Coverage">
          <ul className="space-y-1">
            {d.learning_coverage.topics.map((topic, i) => (
              <li key={i} className="flex items-start gap-2 text-sm text-gray-700">
                <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-[#FF6B1F] shrink-0" />
                {topic}
              </li>
            ))}
          </ul>
        </PrintSection>

        {/* Student Performance */}
        <PrintSection icon={<TrendingUp size={14} />} title="Student Performance">
          <p className="text-sm text-gray-700 leading-relaxed">{d.student_performance.narrative}</p>
        </PrintSection>

        {/* Next Steps */}
        <PrintSection icon={<ArrowRight size={14} />} title="Next Steps">
          <ul className="space-y-1">
            {d.next_steps.topics.map((topic, i) => (
              <li key={i} className="flex items-start gap-2 text-sm text-gray-700">
                <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-gray-400 shrink-0" />
                {topic}
              </li>
            ))}
          </ul>
        </PrintSection>

        {/* Teacher's Note */}
        {(report.teacher_note || d.teacher_note) && (
          <PrintSection icon={<Pencil size={14} />} title="Teacher's Note">
            <p className="text-sm italic text-gray-700">
              &ldquo;{report.teacher_note || d.teacher_note}&rdquo;
            </p>
          </PrintSection>
        )}

        {/* Footer */}
        <div className="mt-10 pt-6 border-t border-gray-200">
          <p className="text-[10px] text-gray-400 text-center">
            Generated by Super Sheldon PTM Agent · Sheldon Labs
          </p>
        </div>
      </div>
    </>
  );
}

function PrintSection({ icon, title, children }: { icon: React.ReactNode; title: string; children: React.ReactNode }) {
  return (
    <div className="mb-6">
      <div className="flex items-center gap-1.5 mb-3">
        <span className="text-[#FF6B1F]">{icon}</span>
        <h2 className="text-xs font-semibold text-gray-500 uppercase tracking-widest">{title}</h2>
      </div>
      {children}
    </div>
  );
}

function PrintStat({ label, value }: { label: string; value: string | number }) {
  return (
    <div className="bg-gray-50 rounded-lg p-3 border border-gray-100">
      <p className="text-xl font-bold text-gray-900" style={{ fontFamily: "'Plus Jakarta Sans', Inter, system-ui" }}>{value}</p>
      <p className="text-[10px] text-gray-400 mt-0.5">{label}</p>
    </div>
  );
}
